name: push to render

on:
  - push

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: test Docker ins
        run: |
          uname -a
          docker -v

      - name: ls
        run: ls
