name: push to render

on:
  - push

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Docker auth
        run: sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: Build Image
        run: sudo docker build -t webpage .

      - name: Tag image
        run: sudo docker tag webpage ${{ secrets.DOCKER_USERNAME }}/webpage:latest

      - name: upload image to dockerhub
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/webpage:latest
